//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopyOnWrite.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState WindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["WindowState"]));
            }
            set {
                this["WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\_bak")]
        public string ToFolder {
            get {
                return ((string)(this["ToFolder"]));
            }
            set {
                this["ToFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public int Col_FileName_Width {
            get {
                return ((int)(this["Col_FileName_Width"]));
            }
            set {
                this["Col_FileName_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("236")]
        public int Col_FullPath_Width {
            get {
                return ((int)(this["Col_FullPath_Width"]));
            }
            set {
                this["Col_FullPath_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("154")]
        public int Col_TimeStamp_Width {
            get {
                return ((int)(this["Col_TimeStamp_Width"]));
            }
            set {
                this["Col_TimeStamp_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>\.sln$|\.vcxproj$|\.c$|\.cpp$|\.h$|\.rc$|\.dlg$|\.htm$|\.html$</string>
  <string />
  <string />
  <string>match nothing</string>
  <string />
  <string />
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection IsMatch {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["IsMatch"]));
            }
            set {
                this["IsMatch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>C:\_qdev\</string>
  <string>C:\_T</string>
  <string>c:\_qdev_data</string>
  <string>C:\Users\trichards</string>
  <string>c:\_CopyOnWrite</string>
  <string>h:\_OneNote</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FromFolder {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FromFolder"]));
            }
            set {
                this["FromFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1, 0, 667, 1080")]
        public global::System.Drawing.Rectangle WindowPosition {
            get {
                return ((global::System.Drawing.Rectangle)(this["WindowPosition"]));
            }
            set {
                this["WindowPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfBoolean xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <boolean>false</boolean>
  <boolean>false</boolean>
  <boolean>false</boolean>
  <boolean>false</boolean>
  <boolean>false</boolean>
  <boolean>false</boolean>
</ArrayOfBoolean>")]
        public bool[] Disable {
            get {
                return ((bool[])(this["Disable"]));
            }
            set {
                this["Disable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfInt xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <int>434</int>
  <int>632</int>
  <int>632</int>
  <int>632</int>
  <int>632</int>
  <int>279</int>
</ArrayOfInt>")]
        public int[] SplitterPos {
            get {
                return ((int[])(this["SplitterPos"]));
            }
            set {
                this["SplitterPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("56")]
        public int Col_Tab_Width {
            get {
                return ((int)(this["Col_Tab_Width"]));
            }
            set {
                this["Col_Tab_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>qwapp\.c$|dlldata\.c$|(_p|_i|_h)\.(c|h)$|_manifest.rc$|\ \-\ Copy|Debug</string>
  <string>application$|cache$|exe$|pdb$|tmp$|manifest$|tlog$|resources$|suo$|FileListAbsolute.txt|Debug|OFXLOG.DAT|mp3$|png$|dll$|msi$|cab$|appinfo$vmx$|vmxf$|cache</string>
  <string>qdf$|dat$|qdf-backup$|_sync_perf.txt$</string>
  <string>^Cookies|^ntuser|^SyncData|^Current|^~|^FavIcons|tmp$|^Preferences|winprf$|Default$</string>
  <string>application$|cache$|exe$|pdb$|tmp$|manifest$|tlog$|resources$|suo$|FileListAbsolute.txt|Debug|OFXLOG.DAT|mp3$|png$|dll$|deploy$|publish</string>
  <string />
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Negative {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Negative"]));
            }
            set {
                this["Negative"] = value;
            }
        }
    }
}
